name: auto-merge-prs

on:
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
    paths:
      - 'Activities/**'

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Generate App Token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: Auto-merge PRs
        uses: pascalgn/automerge-action@v0.16.0
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          merge-method: squash
